Updated composer dependencies
sulu/SuluThemeBundle pull request #5
Opened 2016-12-14 14:58 UTC by wachterjohannes

This PR updates composer.json to upgrade to symfony3.

2016-12-14 15:20 UTC, danrot requested changes

2016-12-14 15:20 UTC, danrot commented on composer.json
> +        "liip/theme-bundle": "^1.4"
Shouldn't that also be `~1.4`?

2016-12-14 15:31 UTC, wachterjohannes commented on composer.json
> +        "liip/theme-bundle": "^1.4"
right

2016-12-14 15:34 UTC, wachterjohannes commented on composer.json
> +        "liip/theme-bundle": "^1.4"
@danrot fixed

2016-12-15 06:56 UTC, wachterjohannes commented
@danrot there is currently a bug in the theme-bundle with 3.2.1 https://github.com/liip/LiipThemeBundle/pull/159/files i would say we will wait for this fix.

2016-12-15 07:01 UTC, wachterjohannes commented
here the link to the issue https://github.com/liip/LiipThemeBundle/issues/157

2016-12-16 06:36 UTC, wachterjohannes commented
can be merged now (: https://github.com/liip/LiipThemeBundle/releases/tag/1.4.3

2016-12-16 07:05 UTC, danrot approved these changes

2016-12-16 07:16 UTC, merged